### ISSUE TITLE
Addition of More Templates

### ISSUE THREAD

**Issue by dipankardas011** [kubeshop/monokle-default-templates-plugin#3]
Can add Persistent-volume-claim, persistent-volume and statefulsets?

**Comment by olensmar** [comment]
Thanks @dipankardas011 - definitely! 

Which input configuration properties would you suggest we add to the wizard for each of these?

**Comment by dipankardas011** [comment]
> Thanks @dipankardas011 - definitely!
> 
> Which input configuration properties would you suggest we add to the wizard for each of these?

Are you asking about which Kubernetes object I want to add?

**Comment by olensmar** [comment]
no - i mean for each of these templates (PVC, PV, SS) - what should the user have to specify apart from name/namespace - and what yaml should we generate based on the users input? 

(we can try to figure this ourselves - I just wanted to see if you had any specific requests)

**Comment by dipankardas011** [comment]
okay understood

**Comment by dipankardas011** [comment]
PV : `labels`, `storage capacity`, `accessModes`, `reclaim policy`
PVC : `labels` , `request storage`, `accessMode`
Statefuleset : `labels`, `serviceName`, `replicas`, `container name, image`, `accessMode`

**Comment by olensmar** [comment]
awesome - thank you!

**Comment by dipankardas011** [comment]
I have made it so can I send the pictures of the template.yaml for each of them

**Comment by olensmar** [comment]
great - or just attach them in a gist?

**Comment by olensmar** [comment]
or open a PR to this repo with them...

**Comment by dipankardas011** [comment]
okay making a PR🙂

**Comment by chlete** [comment]
Thanks for your proposal and PR @dipankardas011 ! 👍

**Comment by dipankardas011** [comment]
In the `author` : ?? 

- [ ] should I put `kubeshop.io`

![code](https://user-images.githubusercontent.com/65275144/164703965-44644598-4f73-483e-94be-ce90bb673f65.png)

**Comment by chlete** [comment]
Hi @dipankardas011 

You did it, you are the author :)

**Comment by chlete** [comment]
Whatever makes you feel comfortable. We appreciate what you did a lot, that's why we think you can put your name 👍

**Comment by dipankardas011** [comment]
Thanks

**Comment by dipankardas011** [comment]
Leaving a comment, as the PR #4 has not been reviewed🙂

**Comment by dipankardas011** [comment]
Thanks for merging PR #4
